#!/bin/bash

echo "🚀 RENDER DEPLOYMENT SCRIPT"
echo "=========================="
echo ""

echo "📋 PRE-DEPLOYMENT CHECKLIST:"
echo "1. ✅ Backend code is ready"
echo "2. ✅ render.yaml configuration created"
echo "3. ✅ CORS settings updated for production"
echo "4. ✅ Port configuration added"
echo ""

echo "🔧 MANUAL STEPS REQUIRED:"
echo "========================="
echo ""
echo "1. Go to https://render.com and sign in"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repository: snehshah74/ConversaAI"
echo "4. Configure service settings:"
echo "   - Name: conversa-ai-backend"
echo "   - Environment: Python 3"
echo "   - Build Command: pip install -r backend/requirements.txt"
echo "   - Start Command: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "5. Set Environment Variables:"
echo "   - GOOGLE_API_KEY = AIzaSyAwmdLH5t56tH7oy5P_4BGgYNdwshlN-lU"
echo "   - ENVIRONMENT = production"
echo "   - DATABASE_URL = (your Supabase URL or leave empty)"
echo "   - PORT = 8000"
echo ""
echo "6. Click 'Create Web Service'"
echo ""

echo "⏱️  DEPLOYMENT TIME:"
echo "Build: ~5-10 minutes"
echo "First request: ~30 seconds (cold start)"
echo ""

echo "🧪 TEST YOUR DEPLOYMENT:"
echo "========================="
echo "After deployment, test these endpoints:"
echo ""
echo "# Health check"
echo "curl https://conversa-ai-backend.onrender.com/api/health"
echo ""
echo "# Root endpoint"
echo "curl https://conversa-ai-backend.onrender.com/"
echo ""
echo "# Agents endpoint"
echo "curl https://conversa-ai-backend.onrender.com/api/agents"
echo ""

echo "📝 NEXT STEPS AFTER DEPLOYMENT:"
echo "==============================="
echo "1. Test all API endpoints"
echo "2. Update frontend with new API URL"
echo "3. Deploy frontend to Vercel"
echo "4. Test full application flow"
echo ""

echo "🎯 Your backend will be live at:"
echo "https://conversa-ai-backend.onrender.com"
echo ""

echo "✅ Ready to deploy! Follow the manual steps above."
