services:
  - type: web
    name: conversa-ai-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 8000
